# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'cmbCodeChallenge' do
  use_frameworks!

  # Pods for cmbCodeChallenge
  pod 'Alamofire', '~> 4.4'

  target 'cmbCodeChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cmbCodeChallengeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
